### ISSUE TITLE
Convert Favicon from jpg to png image

### ISSUE THREAD

**Issue by sbshah97** [salman-bhai/NITKWebsite#17]
1. Just use any online image convertor to convert a png image to a favicon
2. Make sure you use the favicon for all devices including mobiles and tablets!

**Comment by sbshah97** [comment]
@rashika97 what progress on this? This the most easiest of them all!

**Comment by rashika97** [comment]
done. sorry didnt know about this task.

**Comment by sbshah97** [comment]
No problem!
