### ISSUE TITLE
Department Facilities

### ISSUE THREAD

**Issue by sbshah97** [salman-bhai/NITKWebsite#32]
* Reorganise the page's data to add provisions for adding images and more relevant information for the same page!

* Take a look at this link: http://infotech.nitk.ac.in/facilities

* Make sure to re-design the entire page in a proper manner!

* Name the page as `department_facilities.html`

* Kindly look at the `central_facilities.html` page to see how to do it!

**Issue assigned to Utkarsh**

**Comment by sbshah97** [comment]
Under review

**Comment by Hrily** [comment]
@utkarsh23 
Is the page list (General Facilities, Lab Facilities, etc) fixed???
It should be moving as we scroll the page, so that we can jump to any page from any position
Try to come up with similar technique in small screens
