### ISSUE TITLE
Make a separate template website for Convocations

### ISSUE THREAD

**Issue by sbshah97** [salman-bhai/NITKWebsite#44]
* Create a template website where all convocation details can be added!
* This website should also allow students to view a video of the convocation! Use a YouTube iFrame and embed it inside the page!
* Apart from this all other details of the convocation should be presented in a in a better format with images!
* You are free to use your creativity and can check out convocation of national and international universities and engineering colleges as well!
* A link of the current page is given as: http://nitk.ac.in/news-announcments-tenders/14-th-annual-convocation-november-12-2016

**Comment by sbshah97** [comment]
Any progress, @rashika97?

**Comment by rashika97** [comment]
yes main page has been uploaded. if any changes are required then let me know.

**Comment by sbshah97** [comment]
Any progress on further pages in this?

**Comment by sbshah97** [comment]
Kindly view the existing code and also MIT's site and make changes accordingly!
