### ISSUE TITLE
index.html Page doesn't work in mobile devices

### ISSUE THREAD

**Issue by mishal23** [salman-bhai/NITKWebsite#59]
Carousel Class has been used in index.html and Carousel class doesn't work in mobile devices
ScreenShot attached!
![screenshot 82](https://cloud.githubusercontent.com/assets/21958074/25986434/94cf9628-370d-11e7-9cac-35f47aaab71d.png)

**Comment by sbshah97** [comment]
Oh yeah that's been disabled after asking Sowmya ma'am. It's been done on purpose!
