### ISSUE TITLE
Contact Us Page

### ISSUE THREAD

**Issue by sbshah97** [salman-bhai/NITKWebsite#6]
* In the form, add a Recaptcha while adding the form.
* All questions have to be compulsorily be filled.
* All email IDs should be converted into images. (Use text to images to prevent web scraping)

**Comment by sbshah97** [comment]
@rashika97 Kindly add a Recaptcha to the existing structure of the form!
This is to be done after the form has been filled!

**Comment by rashika97** [comment]
done with the issues. the conversion of email id to images has to be done
in the back end i guess.

**Comment by sbshah97** [comment]
Good work!
