### ISSUE TITLE
Ongoing Sponsored Projects at NITK

### ISSUE THREAD

**Issue by sbshah97** [salman-bhai/NITKWebsite#67]
Kindly make this page more attractive by using some kind of styling! Use your creativity to what you think is the best!

http://nitk.ac.in/research/ongoing-sponsored-projects-2014-2015

**Comment by mohittahiliani** [comment]
I suggest we provide two filters / dropdown for this page:

1. Department (can be selected from a dropdown or anything better)
2. Completed / Ongoing (I'm aware that only the ongoing projects are listed currently, but it is better to have a record of completed ones too).

**Comment by sbshah97** [comment]
We can have tabs to filter completed and ongoing sir! Two tabs in the same HTML Page.

Whereas for Department we can look for better options than the current accordion style that is present currently!

**Comment by mohittahiliani** [comment]
I agree, the current style for Department listing looks odd and moreover, exhaustive. Try to make it short and clear.

Tabs should be fine for completed and ongoing.

**Comment by mishal23** [comment]
Sure @mohittahiliani Sir , I'll try my best to make it short & clear!

**Comment by sbshah97** [comment]
@mishal23 what is the progress?
