### ISSUE TITLE
Few checks to make the frontend integration friendly with Backend generators 

### ISSUE THREAD

**Issue by akshayrvnkr** [salman-bhai/NITKWebsite#75]
1. Ensure that you have appropriate HTML comments placed around locations which needs to be rendered through partials.
**Partials refers to** the main \<div\> and the contents within it as a separate file without any \<html\> or \<body\> tags, it should only contain that content.
Example:
  a. The Header of the website
  b. The search bar within the header also should be a partial
  c. The navigation bar
  d. The footer
  e. A generic news bulletin for one category (so that the same template can be rendered in any other page if necessary)
  f. The Contact Us forms
  and few others things that will come along.

2. Either makes the grid flexible or keep the content width fixed. The website looks weird in 1080p. The areas in Green are still fine but the headers and navbar look misaligned with respect to the content unlike the current NITK website which has fixed width layout.
![screenshot 12](https://user-images.githubusercontent.com/7658939/27682629-f507a69a-5ce0-11e7-8ac2-8acd46309e4a.png)

3. Decide on the placeholders for content, the grid layout you have in the frontend and how it is going to be stored on the backend and appropriately 'ID' the locations for easier integration later with the backend.

@salman-bhai .. Discuss and try implementing the changes.

**Comment by sbshah97** [comment]
@akshayrvnkr what does 'ID' the location refer to?

**Comment by akshayrvnkr** [comment]
Basically just have a meaningful id for each div etc so that we can easily integrate those locations later..

**Comment by sbshah97** [comment]
Okay will do so accordingly!

**Comment by manalig7** [comment]
# Closing Issue

* All codes have been moved to IRIS GitLab. **_Kindly refer them_**
