### ISSUE TITLE
Non Teaching Staff Members

### ISSUE THREAD

**Issue by sbshah97** [salman-bhai/NITKWebsite#9]
The following fields should be added for Non Teaching Staff:
* Name
* Designation
* Contact Information
* Educational Qualification
* Workshops attended
* Additional Responsibilities

**Comment by sbshah97** [comment]
@hafeezali Kindly send in a PR with lesser number of files. Just adding the HTML file is fine!

**Comment by hafeezali** [comment]
@salman-bhai added the HTML file
